name: Auto-merge Lovable changes
on:
  push:
    branches: ['lovable/design/*']

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Merge to develop
        run: |
          git fetch origin
          git checkout develop
          git merge origin/\${{ github.ref_name }} --no-ff -m 'Auto-merge Lovable UI changes'
          git push origin develop
